owner: machado-lab
repo: rabapp-upptime

sites:
  - name: RABapp™
    url: https://rabapp.org
    icon: https://rabapp.org/favicon.ico
    maxResponseTime: 1000
  - name: RABapp™ API
    url: https://api.rabapp.org/health/ready
    icon: https://rabapp.org/favicon.ico
    maxResponseTime: 1000
  - name: RABapp™ accounts
    url: https://api.rabapp.org/auth/realms/rabapp/.well-known/openid-configuration
    icon: https://rabapp.org/favicon.ico
    maxResponseTime: 1000

status-website:
  name: RABapp™
  introTitle: RABapp™ status page
  introMessage: |
    This page provides status information on the services that are part of RABapp™.
    Check back here to view the current status of the services listed below.
    If you are experiencing an issue not listed here, please contact **machado-lab@ncsu.edu**.
  baseUrl: /rabapp-upptime
  icon:  https://raw.githubusercontent.com/machado-lab/rabapp-upptime/master/assets/favicon.svg
  faviconSvg:  https://raw.githubusercontent.com/machado-lab/rabapp-upptime/master/assets/favicon.svg
  themeUrl: https://machado-lab.github.io/rabapp-upptime/style.css
  logoUrl: https://rabapp.org/favicon.ico


i18n:
  footer: ""


assignees:
  - nuttysunday
  - debling

workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "0 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 * * * *"
  uptime: "*/5 * * * *"