owner: machado-lab 
repo: rabapp-upptime

sites:
  - name: RABapp
    url: https://api.rabapp.org/health/ready

status-website:
  baseUrl: /rabapp-upptime
  name: RABapp status
  themeUrl: https://machado-lab.github.io/rabapp-upptime/style.css